### ISSUE TITLE
Replace elevation marker with inline SVG

### ISSUE THREAD

**Issue by skirridsystems** [Raruto/leaflet-elevation#102]
One of my users commented that the marker looks a bit low-res and might work better as SVG. I've submitted this as an issue rather than a PR as I'm not sure of the best place to leave the SVG in the source. The SVG is embedded in the CSS so the source file doesn't need to be included in the distribution.

```css
.elevation-position-icon:before {
  background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 8.5 8.5'%3E%3Ccircle cx='4.2' cy='4.2' r='2.1' style='fill:%23fff;stroke-linejoin:round'/%3E%3Ccircle cx='4.2' cy='4.2' r='0.5' style='fill:%23235062;stroke-linejoin:round;stroke-width:0.5'/%3E%3Ccircle cx='4.2' cy='4.2' r='1.2' style='fill:none;stroke-linejoin:round;stroke-width:0.2;stroke:%23235062'/%3E%3Ccircle cx='4.2' cy='4.2' r='2.1' style='fill:none;stroke-linejoin:round;stroke-width:0.5;stroke:%23235062'/%3E%3C/svg%3E") no-repeat center center / contain;
  content: "";
  width: 100%;
  height: 100%;
  display: inline-block;
}
```

I can't attach the SVG but this is the file content before URL encoding:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 8.5 8.5">
    <circle cx="4.2" cy="4.2" r="2.1" style="fill:#fff;stroke-linejoin:round"/>
    <circle cx="4.2" cy="4.2" r="0.5" style="fill:#235062;stroke-linejoin:round;stroke-width:0.5"/>
    <circle cx="4.2" cy="4.2" r="1.2" style="fill:none;stroke-linejoin:round;stroke-width:0.2;stroke:#235062"/>
    <circle cx="4.2" cy="4.2" r="2.1" style="fill:none;stroke-linejoin:round;stroke-width:0.5;stroke:#235062"/>
</svg>
```

I created it in Inkscape and then used https://petercollingridge.appspot.com/svg-optimiser and https://yoksel.github.io/url-encoder/

The same could be done with the pushpin marker, but I don't use that one so I'll leave it as an exercise for someone else!
