### ISSUE TITLE
Hide altitude-profile

### ISSUE THREAD

**Issue by bknt011** [Raruto/leaflet-elevation#167]
How can I switch off or hide the altitude profile?

**Comment by Raruto** [comment]
Hi bknt011,
you can use the following option:
```js
// Display altitude info: true || "summary"
altitude: 'summary',
```
in conjunction with some css rules:
```css
.elevation-control .y.axis.left.altitude,
.elevation-control .legend-item.legend-altitude {
  display: none;
}
```

_Greetings,
Raruto_
