### ISSUE TITLE
Override WordPress theme styles

### ISSUE THREAD

**Issue by hencheck94** [Raruto/leaflet-elevation#30]
Hi,
Sorry for asking again a maybe stupid question.

After applying your solution for [my first problem](https://github.com/Raruto/leaflet-elevation/issues/29#issuecomment-565842085) (adding a `leaflet-map-container` element around the map) , I stumbled upon another problem.

When using the standard Wordpress Theme Twenty Twenty, the map and altitude graph get displayed as expected in (Firefox, Chrome, Safari). But when changing the theme to, in my case, [Fabulist](https://wordpress.org/themes/fabulist/) it isn't anymore:

- In **Safari** it shows a map without the trail and without the altitude graph.
- In **Firefox** it shows the map again without the trail visible but with an somewhat disturbed altitude graph under it.. 

![safari](https://user-images.githubusercontent.com/58913302/70905536-cf6dd700-200c-11ea-8801-3d671ec9ded8.jpg)
![firefox](https://user-images.githubusercontent.com/58913302/70905537-cf6dd700-200c-11ea-9efe-b56aa19adfa3.jpg)

Do you have any idea what in the Theme may cause this and how to prevent it?
Thank you in advance!

[my page](http://gr20.jan-unterwegs.de/2019/12/15/test/)

**Comment by Raruto** [comment]
Hi Jan,

in your [parent theme](https://wordpress.org/themes/fabulist/) you have the following css rule:
```css
svg {
    width: 15px;
    height: 15px;
    display: inline-block;
    vertical-align: middle;
}
```
so in your [child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/) you would insert something like this:

```css
.leaflet-map-container svg {
    height: auto;
    width: auto;
}
```
As you can see, this happens because the elevation **chart profile** is a valid **SVG element**.
