### ISSUE TITLE
Override Joomla theme styles

### ISSUE THREAD

**Issue by elecoest** [Raruto/leaflet-elevation#50]
Hello,

I have a problem with integration of this plugin in a joomla html page: I lose the **`followMarker`** functionality. For an example file, in simple html it's work fine, if I copy/paste the code in a joomla page I loose the functionality. The map move along the gpx trace when i scroll the histogram but without any pin and information.

I haven't any error in console.

_Do you have any idea ?_

**Comment by Raruto** [comment]
Hi Emmanuel,

some cms / visual editors don't really like having javascript inserted directly into post content, did you also check that there are no "nesting errors" in the generated html?

**PS** you can use CTRL+U or https://validator.w3.org/ to verify your code.

_Have a nice day,
Raruto_

**Comment by elecoest** [comment]
sorry, no specific error. you can test by yourself :  https://www.t2area.com/triathlon-m-d-enghien-95.html

PS : Many thanks for the translation :)

**Comment by Raruto** [comment]
Maybe I'm wrong, but on that page I don't see any map / graph...

**Comment by elecoest** [comment]
I'm awfully sorry. In normal case, this map is only for user registred. 

I patched the page. It's ok now. sorry :/

**Comment by Raruto** [comment]
This issue is somehow related to https://github.com/Raruto/leaflet-elevation/issues/30

In your theme / plugins you have these pre-defined rules:

**uikit.css**

```css
svg {
    max-width: 100%;
    height: auto;
    box-sizing: border-box;
}
```

**nucleus.css**

```css
iframe, svg {
    max-width: 100%;
}
```

so in your css theme you would insert something like this:

```css
.leaflet-elevation-pane > svg {
    max-width: unset;
}
```

_Regards,
Raruto_
